version: lastest

services:
  db:
    container_name: postgres
    build: 
      context: .
      dockerfile: postgresDockerFile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    networks:
      - postgres-connection

  

networks:
  postgres-connection:
    driver: bridge